env:
  global:
    - BINSTAR_USER: menpo
  matrix:
    - PYTHON_VERSION: 2.7  # Only need to build one kind because non-Python

install:
- wget https://raw.githubusercontent.com/jabooth/condaci/v0.2.1/condaci.py -O condaci.py
- python condaci.py setup $PYTHON_VERSION --channel $BINSTAR_USER
- export PATH=$HOME/miniconda/bin:$PATH

script:
- python condaci.py auto ./conda --binstaruser $BINSTAR_USER --binstarkey $BINSTAR_KEY

notifications:
  slack:
    rooms:
      - menpo:19gyWImMkOfCj0iDAgTbDlDA
    on_success: :change
    on_failure: :change
  email: false
